name: Build and deploy to Azure via ACR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nestjs-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD_1 }}
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nestjs-backend:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nestjs-backend:latest

#      - name: Deploy to Azure App Service using Docker image
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
#          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/nestjs-backend:latest
